### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by gspe** [TronWatch/Desktop-Wallet#145]
I'd like to try last version that support ledger nano on my linux distribution, would be nice to have instruction about how to build from source code.
Thanks.

**Comment by ColonelJ** [comment]
Try this, it worked for me:

* Download Node.js from [the website](https://nodejs.org/en/) to get a recent enough version and put the '`bin/`' on the PATH (LTS version is fine)
* Install yarn
* Checkout the Desktop-Wallet source master branch using Git (don't download from releases since it references the wrong commit)
* Do '`yarn install`'
* Do '`yarn package-linux`'
* You should find `TronWatch-1.0.12-x86_64.AppImage` in the `release/` directory as well as Debian package if you want it (also '`tronwatch`' in `release/linux-unpacked`)
