### ISSUE TITLE
Serious issues with import/export!

### ISSUE THREAD

**Issue by alojzjakob** [TronWatch/Desktop-Wallet#97]
Hi,

i exported keys from TronWatch and tried to import to Android wallet i also found on official tron.network website (https://github.com/Dryec/tron-wallet-android),
but  mobile wallet expects 64 character length private key.
TronWatch gives 128 key when exported.

Also tried with 24 words, on mobile wallet it created totally different private key and public address!

I am confused now. which one is correct?
Will i lose my funds if you decide to reduce key to 64 as they did?
What if they decide to increase key to 128, and i lose all on that wallet too??

I am sorry but this is not ok.

Thank you!

**Comment by metjm** [comment]
Hey, we currently use the bip39 seed as private key. 

The 24 word import on android is different in the mobile wallet because they decode it as if it was encoded using the password string "pass" as you can see here: https://github.com/Dryec/tron-wallet-android/blob/83d2d8aca11ca8ef2672ba76a59e88b9ba3e0178/app/src/main/java/com/eletac/tronwallet/wallet/ImportWalletActivity.java#L325
We've notified them of this a couple weeks ago, not sure why this is still the case.  

When we created the wallet for the programming competition there were no guidelines what kind of seed should be used, so we decided on what we currently use. You will not lose your funds either way. For example you can import 64 character long private keys into our wallet just fine and you will get the same address that tronscan gives you. Our import and exports generates the exact same seed that you can see here when you enter 24 words: http://bip32.org/

**Comment by alojzjakob** [comment]
Hi,

thank you for really fast and in-depth reply!
i wrote the same thing on their github: https://github.com/Dryec/tron-wallet-android/issues/13
lets see if it will give them a push!
anyway, these things should not happen, all wallets listed on the production website should be consistent, you said that you decided.
If mobile wallet is broken, it should be removed from the website! Same applies in opposite direction.

You want to say that your wallet will import 64 char key correctly, you wrote handler for that case, give me an example please just to confirm :)

**Comment by metjm** [comment]
I 100% agree that things should be more consistent.

 It is important to note that the android wallet is not broken, it is still deterministic in generating a private key from the words, it just generates a different one. But that different one is not broken or wrong, its simply different.   

`D70465590A7AE060D72DE2363120524DE310BF97D220B4E7B559DA1CB9E0C453` <- example of a 64 char private key, you can import that in tronscan or our wallet and it will generate the same publickey. I'm guessing it will also create the same on the android one although I haven't tested that wallet.

**Comment by alojzjakob** [comment]
Ok, so, you want to say that i should first create keys in their wallet, and then import in yours if i want access to same wallet on mobile and desktop?
Clearly i will need to import private key, not 24 words, snce it will generate totally different private key :)

**Comment by metjm** [comment]
Yes, that is probably the best course of action if you want to use both at the moment. We are talking to other wallets to make this stuff consistent but we're kinda swamped with projects right now so tasks like this get pushed back a lot.
